# Generated by Django 5.1.5 on 2025-02-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summary', '0002_summary_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='type',
            new_name='content_type',
        ),
        migrations.AddField(
            model_name='summary',
            name='user_prompt',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
