# Generated by Django 5.1.5 on 2025-02-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summary', '0003_rename_type_summary_content_type_summary_user_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='favorites',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
