# Generated by Django 5.1.5 on 2025-02-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summary', '0004_summary_dislikes_summary_favorites_summary_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
