# Generated by Django 5.1.5 on 2025-02-12 20:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summary', '0005_summary_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=list, size=None),
        ),
    ]
