# Generated by Django 5.1.5 on 2025-02-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summary', '0007_summary_category_summary_raw_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
