# Generated by Django 5.1.5 on 2025-02-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summary', '0008_alter_summary_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='raw_text',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
    ]
