# Generated by Django 5.1.5 on 2025-02-17 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Summary', '0009_alter_summary_raw_text'),
    ]

    operations = [
    ]
