# Generated by Django 5.1.5 on 2025-02-18 00:06

import Summary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summary', '0010_auto_20250218_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='id',
            field=models.BigIntegerField(default=Summary.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='summary',
            name='raw_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
