# Generated by Django 5.1.5 on 2025-03-06 21:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summary', '0011_alter_summary_id_alter_summary_raw_text'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='likes',
        ),
        migrations.AlterField(
            model_name='summary',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='summary',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_summaries', to='Users.userdata'),
        ),
        migrations.AddField(
            model_name='summary',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_summaries', to='Users.userdata'),
        ),
        migrations.AddField(
            model_name='summary',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_summaries', to='Users.userdata'),
        ),
    ]
