# Generated by Django 5.1.5 on 2025-03-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summary', '0012_remove_summary_dislikes_remove_summary_favorites_and_more'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_by', to='Summary.summary'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='Summary.summary'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favored_by', to='Summary.summary'),
        ),
    ]
